### ISSUE TITLE
建议修改部分方案定义文件 `schema/version:` 及词典文件的 `version:`

### ISSUE THREAD

**Issue by lotem** [biopolyhedron/rime_schemata#1]
比较版本字符串的规则是：
用 `.` 切分版本字符串，从左到右依次比较每一个组成部分，直到确定大小或达到某个字符串的结尾；
如果已经比较过的部分相等，先达到末尾的小于有剩余部分的。
比较每一个由 `.` 划分的部分，规则是先按数值比较，如果数值相同，再将（剩余的）非整数字符串按字典顺序比较。
例如有 `"10a > 9b"`, `"zero.0" > "one.1"`

`"poly2000.01.01"` 及 `"poly 2000.01.01"` 不符合通常的版本号写法。
可以改为 `"2000.01.01.poly"`——总是先做数值比较，`poly` 只作标记，因为字符串的大小在这里没有实际意义。

**Comment by osfans** [comment]
順便請教下，columns默認是什麼？是text code weight吧？
看到韓語裏面是“漢字   轉寫    한글”，這樣第三列是否有問題？

**Comment by osfans** [comment]
[dict_settings.cc#L86](https://github.com/rime/librime/blob/develop/src/dict/dict_settings.cc#L86)

``` c++
  if ((*this)["columns"].IsNull()) {
    // default
    if (column_label == "text") return 0;
    if (column_label == "code") return 1;
    if (column_label == "weight") return 2;
    return -1;
  }
```

看來三列依次是text code weight，那[hangyl_hanja.dict.yaml#L11290](https://github.com/biopolyhedron/rime_schemata/blob/master/hangyl_hanja.dict.yaml#L11290)第三列有問題，會當成詞頻處理。

**Comment by lotem** [comment]
因为无法解析成词频，每读一行会产生一条警告级日志。
如果这列没用，可在词典 YAML 部分定义 `columns:`，给这一列指定任意的名字都中。
@osfans 欢迎 Pull Request

**Comment by osfans** [comment]
瞭解了。這是多面體的git，我要到rime那邊去pull request吧？
話說，rime-aca/schemata.git中也有韓語方案。

沒有專門的comment列，不然這第三列設置成comment也不錯。

關於comment，我看雪齋的emoji把code和comment放一起，
然後在`speller/algebra`中解析出code，在`translator/comment_format`中解析出comment。
這倒也是一個可行的方案。

```
#天氣
☀ sunny;tian'qi`weather   10908516
☔ rain;tian'qi`weather    951774
⛈ storm;tian'qi`weather
⛆ haze;tian'qi`weather
⛅ cloudy;tian'qi`weather  771487
☁ cloud;tian'qi`weather   2024540
❄ snow;tian'qi`weather    2407391
⚡ lightening;tian'qi`weather  952903
🌊    tsunami;tian'qi`weather 1043014
🌀    typhoon;tian'qi`weather 1434111
🌂    rain;tian'qi`weather    139837
🌁    fog;tian'qi`weather 68865
```
